// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkIGXlhO6hzR2oghorgLTT8qo9c_TslxI',
    appId: '1:402315566081:web:d5c7a8d1c47dc0dd2db400',
    messagingSenderId: '402315566081',
    projectId: 'email-15e28',
    authDomain: 'email-15e28.firebaseapp.com',
    storageBucket: 'email-15e28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtShKxwDqXRgXfivQCAOgUtqio55jz8Wg',
    appId: '1:402315566081:android:47640ae80b2808b92db400',
    messagingSenderId: '402315566081',
    projectId: 'email-15e28',
    storageBucket: 'email-15e28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1l8pWBVsMd1zok1MKx26YNtKxWuHCR6M',
    appId: '1:402315566081:ios:2ca714fd82e643202db400',
    messagingSenderId: '402315566081',
    projectId: 'email-15e28',
    storageBucket: 'email-15e28.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1l8pWBVsMd1zok1MKx26YNtKxWuHCR6M',
    appId: '1:402315566081:ios:2ca714fd82e643202db400',
    messagingSenderId: '402315566081',
    projectId: 'email-15e28',
    storageBucket: 'email-15e28.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkIGXlhO6hzR2oghorgLTT8qo9c_TslxI',
    appId: '1:402315566081:web:82309afb8668fd612db400',
    messagingSenderId: '402315566081',
    projectId: 'email-15e28',
    authDomain: 'email-15e28.firebaseapp.com',
    storageBucket: 'email-15e28.firebasestorage.app',
  );

}